In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
df=pd.read_csv("affairs.csv")
df


affairs  gender   age  yearsmarried children  religiousness  education  \
0          0    male  37.0         10.00       no              3         18   
1          0  female  27.0          4.00       no              4         14   
2          0  female  32.0         15.00      yes              1         12   
3          0    male  57.0         15.00      yes              5         18   
4          0    male  22.0          0.75       no              2         17   
..       ...     ...   ...           ...      ...            ...        ...   
596        1    male  22.0          1.50      yes              1         12   
597        7  female  32.0         10.00      yes              2         18   
598        2    male  32.0         10.00      yes              2         17   
599        2    male  22.0          7.00      yes              3         18   
600        1  female  32.0         15.00      yes              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 9 columns]

In [32]:
df.isnull().sum()

affairs          0
gender           0
age              0
yearsmarried     0
children         0
religiousness    0
education        0
occupation       0
rating           0
dtype: int64

In [33]:
df['affairs'].unique()

array([ 0,  3,  7, 12,  1,  2])

In [34]:
def affairs(dataframe):
    dataframe.loc[df['affairs']%2==0,'affairs']=0
    dataframe.loc[df['affairs']%2!=0,'affairs']=1
    
    return dataframe
affairs(df)

affairs  gender   age  yearsmarried children  religiousness  education  \
0          0    male  37.0         10.00       no              3         18   
1          0  female  27.0          4.00       no              4         14   
2          0  female  32.0         15.00      yes              1         12   
3          0    male  57.0         15.00      yes              5         18   
4          0    male  22.0          0.75       no              2         17   
..       ...     ...   ...           ...      ...            ...        ...   
596        1    male  22.0          1.50      yes              1         12   
597        1  female  32.0         10.00      yes              2         18   
598        0    male  32.0         10.00      yes              2         17   
599        0    male  22.0          7.00      yes              3         18   
600        1  female  32.0         15.00      yes              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 9 columns]

In [35]:
df.head()

affairs  gender   age  yearsmarried children  religiousness  education  \
0        0    male  37.0         10.00       no              3         18   
1        0  female  27.0          4.00       no              4         14   
2        0  female  32.0         15.00      yes              1         12   
3        0    male  57.0         15.00      yes              5         18   
4        0    male  22.0          0.75       no              2         17   

   occupation  rating  
0           7       4  
1           6       4  
2           1       4  
3           6       5  
4           6       3

In [36]:
y=df.iloc[:,0:1]
y

affairs
0          0
1          0
2          0
3          0
4          0
..       ...
596        1
597        1
598        0
599        0
600        1

[601 rows x 1 columns]

In [37]:
x=df.iloc[:,1:9]
x

gender   age  yearsmarried children  religiousness  education  \
0      male  37.0         10.00       no              3         18   
1    female  27.0          4.00       no              4         14   
2    female  32.0         15.00      yes              1         12   
3      male  57.0         15.00      yes              5         18   
4      male  22.0          0.75       no              2         17   
..      ...   ...           ...      ...            ...        ...   
596    male  22.0          1.50      yes              1         12   
597  female  32.0         10.00      yes              2         18   
598    male  32.0         10.00      yes              2         17   
599    male  22.0          7.00      yes              3         18   
600  female  32.0         15.00      yes              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 8 columns]

In [38]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()
x['gender']=labelencoder_x.fit_transform(x['gender'])
x['children']=labelencoder_x.fit_transform(x['children'])
x

gender   age  yearsmarried  children  religiousness  education  \
0         1  37.0         10.00         0              3         18   
1         0  27.0          4.00         0              4         14   
2         0  32.0         15.00         1              1         12   
3         1  57.0         15.00         1              5         18   
4         1  22.0          0.75         0              2         17   
..      ...   ...           ...       ...            ...        ...   
596       1  22.0          1.50         1              1         12   
597       0  32.0         10.00         1              2         18   
598       1  32.0         10.00         1              2         17   
599       1  22.0          7.00         1              3         18   
600       0  32.0         15.00         1              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 8 columns]

In [39]:
A=pd.concat([y,x],axis=1)
A

affairs  gender   age  yearsmarried  children  religiousness  education  \
0          0       1  37.0         10.00         0              3         18   
1          0       0  27.0          4.00         0              4         14   
2          0       0  32.0         15.00         1              1         12   
3          0       1  57.0         15.00         1              5         18   
4          0       1  22.0          0.75         0              2         17   
..       ...     ...   ...           ...       ...            ...        ...   
596        1       1  22.0          1.50         1              1         12   
597        1       0  32.0         10.00         1              2         18   
598        0       1  32.0         10.00         1              2         17   
599        0       1  22.0          7.00         1              3         18   
600        1       0  32.0         15.00         1              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 9 columns]

In [41]:
A.corr()['affairs']

affairs          1.000000
gender           0.043764
age             -0.000400
yearsmarried     0.026146
children         0.091283
religiousness   -0.058902
education        0.034567
occupation      -0.003749
rating          -0.130423
Name: affairs, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=0)

In [25]:
from sklearn.linear_model import LogisticRegression
logisticregression=LogisticRegression()
logisticregression.fit(train_x,train_y)


/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
y_pred=logisticregression.predict(test_x)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,test_y)

array([[155,  26],
       [  0,   0]])

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,test_y)

0.856353591160221